import {resources,buildings,upgrades,research,achievements,regions,galaxies,galaxySkills,galaxyTypes} from '../data/gameData.js';
import {missions,claimMission,claimAchievement,convertEnergy,discover,storage,normalize,load,save,click,tick,buy,buyUpgrade,buyResearch,prestige,ascend,offline,format,totalProd,cost,achievementProgress} from '../systems/gameEngine.js';
import {navigationReady,discoveryStatus,outpostStatus,upgradeOutpost,skillStatus,upgradeSkill,frontierStatus,advanceFrontier,skillBonus,isGalaxyVisible,galaxyBoosts} from '../systems/exploration.js';
import {cosmicNodes,cosmicBranches,starterCosmicNodes,cosmicStatus,chooseStarter,buyCosmic,cosmicBonuses,starterChoiceAvailable} from '../systems/cosmicEngine.js';
import {civilizationBonuses,civList,specializeColony,setGovernment,togglePolicy,diplomacyAction,establishTrade,buildFleet,resolveWar,buildMega,colonySpecializations,governmentTypes,policyCards,shipClasses,megaProjects,militaryPower} from '../systems/civilization.js';
import {currentEra,nextBreakthroughs,opportunityStatus,startOpportunity,opportunities,buildingMilestone} from '../systems/progression.js';
import '../styles/main.css';
let state=load(),view='command',floating=[],toastTimer,toastMessage='',buyQuantity='1';
const app=document.querySelector('#app');
const nav=[['command','⌂','Command'],['buildings','▦','Infrastructure'],['upgrades','⬡','Upgrades'],['research','⌬','Research'],['galaxy','✦','Galaxy'],['missions','☷','Missions'],['achievements','◆','Achievements'],['stats','◌','Statistics'],['settings','⚙','Settings']];
const expansionNav=[['civilization','♜','Civilization'],['diplomacy','◎','Diplomacy'],['trade','⇄','Trade'],['fleets','⚔','Fleets'],['cosmic','✧','Cosmic Tree'],['megastructures','▰','Megastructures']];
function navItems(){return state.stats.ascensions>0?[...nav,...expansionNav]:nav}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function resourceBar(){return `<div class="resource-bar">${resources.map(r=>`<div class="resource" title="${r.desc}"><span class="res-icon ${r.tone}">${r.icon}</span><div><b>${format(state.resources[r.id]||0)}</b><small>${r.name}</small></div></div>`).join('')}</div>`}
function progressionStrip(){const era=currentEra(state),goals=nextBreakthroughs(state),opportunity=opportunityStatus(state);return `<section class="progression-strip panel"><div class="era-badge"><span class="kicker">CURRENT ERA</span><b>${era.name}</b><small>${era.desc}</small></div><div class="breakthroughs"><span class="kicker">NEXT BREAKTHROUGHS</span><div class="breakthrough-list">${goals.map(g=>`<span class="breakthrough"><b>${g.label}</b><small>${g.kind} · ${g.detail}</small></span>`).join('')||'<span class="muted">The frontier is open. Your next objective will emerge as the empire grows.</span>'}</div></div><div class="opportunity-slot">${opportunity?`<span class="chip hot">${opportunity.name}</span><small>${opportunity.desc}</small>`:`<span class="kicker">OPTIONAL OPPORTUNITY</span><button class="secondary" data-opportunity="${opportunities[0].id}">${opportunities[0].name}</button>`}</div></section>`}
function layout(body){return `<div class="shell"><aside><div class="brand"><div class="brand-mark">✦</div><div><strong>STARFORGE</strong><span>ENERGY EMPIRE</span></div></div><div class="status"><i></i> NETWORK ONLINE <em>v${state.version}.0</em></div><nav>${navItems().map(n=>`<button class="nav ${view===n[0]?'active':''}" data-view="${n[0]}"><span>${n[1]}</span>${n[2]}${n[0]==='missions'?`<b class="badge">${missions(state).filter(m=>!state.claimed[m.id]&&m.progress>=m.goal).length}</b>`:''}</button>`).join('')}</nav><div class="side-foot"><button data-action="save">⇩ Save now</button><button data-view="settings">⚙ Settings</button></div></aside><main>${resourceBar()}<header><div><p class="eyebrow">SECTOR 01 / SOL SYSTEM</p><h1>${navItems().find(n=>n[0]===view)?.[2]||'Command'}</h1></div><div class="header-actions"><span class="live"><i></i> LIVE SIMULATION</span><button class="icon-btn" data-action="boost" title="Activate a 2× production boost for 60 seconds">⚡</button><button class="icon-btn" data-action="export">↥</button></div></header>${progressionStrip()}${body}<div id="toast" class="toast"></div></main></div>`}
function command(){const prod=totalProd(state),energy=state.resources.energy||0;return `<section class="hero-grid"><div class="panel reactor"><div class="panel-top"><span class="kicker">PRIMARY REACTOR</span><span class="chip ${state.boost?'hot':''}">${state.boost?'BOOST ACTIVE':'STABLE'}</span></div><div class="reactor-core"><div class="orbit o1"></div><div class="orbit o2"></div><button class="core-button" id="core"><span class="core-symbol">ϟ</span><span>GENERATE</span><small>+${format(1+(state.upgrades.capacitors?.value||0))} ENERGY</small></button></div><div class="combo"><b>${state.combo}</b><span>COMBO<br/><small>best ${state.stats.bestCombo}</small></span><div class="combo-meter"><i style="width:${Math.min(100,state.combo*2)}%"></i></div></div><div class="reactor-footer"><span>CRITICAL RATE <b>${5+(state.upgrades.precision?.value||0)*5}%</b></span><span>OUTPUT <b>${format(prod.energy||0)}/s</b></span></div></div><div class="right-stack"><div class="panel overview"><div class="panel-top"><span class="kicker">EMPIRE OVERVIEW</span><span class="muted">REAL-TIME</span></div><div class="metrics"><div><small>ENERGY RESERVES</small><strong>${format(energy)}</strong><span class="positive">+${format(prod.energy||0)}/s</span></div><div><small>TOTAL CLICKS</small><strong>${format(state.stats.clicks)}</strong><span class="muted">best combo ${state.stats.bestCombo}</span></div><div><small>EMPIRE MULTIPLIER</small><strong>${((totalMult())*100).toFixed(0)}%</strong><span class="positive">${state.boost?'boosted ×2':'nominal'}</span></div></div></div><div class="panel focus"><div class="panel-top"><span class="kicker">NEXT MILESTONE</span><span class="chip">TUTORIAL 01</span></div><h3>Establish a self-sustaining grid</h3><p>Reach 50 energy per second to unlock the first orbital construction license.</p><div class="progress"><i style="width:${Math.min(100,(prod.energy||0)/.5)}%"></i></div><div class="row"><span>${format(prod.energy||0)} / 50 energy/s</span><button class="text-btn" data-view="buildings">VIEW PATH →</button></div></div></div></section><section class="lower-grid"><div class="panel production"><div class="panel-top"><span class="kicker">PRODUCTION MATRIX</span><button class="text-btn" data-view="buildings">MANAGE ALL →</button></div>${resources.slice(0,7).map(r=>`<div class="production-row"><span class="res-icon ${r.tone}">${r.icon}</span><b>${r.name}</b><div class="mini-progress"><i style="width:${Math.min(100,(prod[r.id]||0)/(Math.max(1,prod.energy||1))*100)}%"></i></div><strong>+${format(prod[r.id]||0)}<small>/s</small></strong></div>`).join('')}</div><div class="panel log"><div class="panel-top"><span class="kicker">EVENT LOG</span><span class="muted">${state.log.length} entries</span></div>${state.log.slice(0,6).map(x=>`<div class="log-row"><i></i><span>${esc(x)}</span></div>`).join('')}</div></section>`}
function buildingPage(){return `<div class="section-intro"><p>Construct systems that turn a spark into a civilization. Costs scale with every level; synergies and research multiply the network.</p><button class="buy" data-action="convert">SELL ENERGY → CREDITS (10:1)</button><div class="buy-toggle"><button class="active" data-buyqty="1">×1</button><button data-buyqty="10">×10</button><button data-buyqty="100">×100</button><button data-buyqty="max">MAX</button></div></div><div class="card-grid">${buildings.map(b=>{const n=state.buildings[b.id]||0,un=Math.max(state.stats.totalEnergy,state.resources.energy)>=b.unlock,price=cost(b,n),milestone=buildingMilestone(state,b.id);return `<article class="building-card ${un?'':'locked'}"><div class="building-head"><div class="building-icon">${b.tag.slice(0,2)}</div><div><h3>${b.name}</h3><span>${b.tag} · LVL ${n}</span></div><b class="level">${n}</b></div><p>${b.desc}</p>${milestone?`<small class="milestone-hint">MILESTONE ${milestone.level}: ${milestone.label}</small>`:''}<div class="output">${Object.entries(b.prod).map(([r,v])=>`<span class="pill ${r}">+${format(v*n)}/${r}/s</span>`).join('')}</div><div class="building-foot"><span>Next <b>${un?format(price)+' ₡':'🔒 '+format(b.unlock)+' ϟ'}</b></span><button class="buy" data-buy="${b.id}" ${un?'':'disabled'}>${un?'BUILD':'LOCKED'}</button></div><div class="card-line"><i style="width:${Math.min(100,n?30+Math.log10(n)*20:4)}%"></i></div></article>`}).join('')}</div>`}
function upgradePage(){return `<div class="section-intro"><p>Install permanent protocols. Every purchase changes the underlying simulation and remains through first prestige.</p></div><div class="upgrade-grid">${upgrades.map(u=>{const got=state.upgrades[u.id],can=Object.entries(u.cost).every(([r,c])=>(state.resources[r]||0)>=c);return `<article class="upgrade ${got?'owned':''}"><div class="upgrade-top"><span class="upgrade-cat">${u.cat}</span>${got?'<span class="owned-mark">INSTALLED</span>':''}</div><h3>${u.name}</h3><p>${u.desc}</p><div class="cost">${Object.entries(u.cost).map(([r,c])=>`<span>${format(c)} ${r}</span>`).join('')}</div><button class="buy" data-upgrade="${u.id}" ${got||!can?'disabled':''}>${got?'ACTIVE':can?'INSTALL':'INSUFFICIENT'}</button></article>`}).join('')}</div>`}
function researchPage(){return `<div class="section-intro"><p>Choose a path through the technology lattice. Completed nodes persist through normal resets.</p><div class="research-bank">⌬ <b>${format(state.resources.research)}</b> research</div></div><div class="research-tree">${research.map(r=>{const done=state.research[r.id],available=!done&&r.req.every(x=>state.research[x])&&state.resources.research>=r.cost;return `<article class="research-node ${done?'done':''} ${available?'available':''}" style="left:${r.x}%;top:${r.y}%" data-research="${r.id}"><span class="node-icon">${done?'✓':'⌬'}</span><div><b>${r.name}</b><small>${done?r.desc:format(r.cost)+' research · '+(r.req.length?'requires '+r.req.join(', '):'available')}</small></div></article>`}).join('')}<svg class="connections" viewBox="0 0 100 100" preserveAspectRatio="none">${research.flatMap(r=>r.req.map(q=>{const a=research.find(x=>x.id===q);return `<line x1="${a.x+4}" y1="${a.y+4}" x2="${r.x+4}" y2="${r.y+4}"/>`})).join('')}</svg></div>`}
function mapPoint(r){return [r.mapX??(1200+(r.x-50)*5),r.mapY??(1200+(r.y-50)*5)]}
function galaxyPage(){
 const visible=regions.filter(r=>isGalaxyVisible(state,r)),discovered=visible.filter(r=>state.exploration.regions[r.id]),boost=galaxyBoosts(state),frontier=frontierStatus(state),skill=skillBonus(state);
 const lines=visible.filter(r=>r.parent&&visible.some(x=>x.id===r.parent)).map(r=>{const a=regions.find(x=>x.id===r.parent),p=mapPoint(a),q=mapPoint(r);return `<line x1="${p[0]}" y1="${p[1]}" x2="${q[0]}" y2="${q[1]}"/>`}).join('');
 const nodes=visible.map(r=>{const p=mapPoint(r),known=state.exploration.regions[r.id],type=galaxyTypes.find(t=>t.id===r.type);return `<button class="map-galaxy ${known?'mapped':'frontier-node'}" style="left:${p[0]}px;top:${p[1]}px" data-select-region="${r.id}" aria-label="${known?r.name:'Uncharted galaxy'}"><i></i><b>${known?r.name:'UNEXPLORED'}</b><small>${known?(type?.name||'Core Galaxy'):'SIGNAL DETECTED'}</small></button>`}).join('');
 const frontierCards=visible.filter(r=>!state.exploration.regions[r.id]).sort((a,b)=>a.cost-b.cost).map(r=>{const status=discoveryStatus(state,r.id),parent=regions.find(x=>x.id===r.parent),type=galaxyTypes.find(t=>t.id===r.type),boosts=Object.entries(type?.boost||{}).map(([k,v])=>`+${(v*100).toFixed(1)}% ${k}`).join(' · ');return `<article class="panel destination-card frontier-destination" id="destination-${r.id}" tabindex="-1"><span class="kicker">CHOICE · VIA ${parent?.name||'UNKNOWN'}</span><h3>${r.name}</h3><p class="galaxy-type-preview"><b>${type?.name||'Unknown Galaxy'}</b> · ${type?.desc||'A new signal is within range.'}</p><p>${r.desc}</p><p class="galaxy-boost">Preview boost: ${boosts||'unique network effect'} · Output: ${Object.entries(r.prod||{}).map(([k,v])=>`+${v} ${k}/s`).join(' · ')}</p><p>Discovery cost: <b>${format(r.cost)} energy</b>${r.tech?` · Requires ${r.tech}`:''}</p><button class="buy" data-region="${r.id}" ${status.ok?'':'disabled'}>${status.label}</button></article>`}).join('');
 const cards=frontierCards+discovered.map(r=>{const type=galaxyTypes.find(t=>t.id===r.type),o=outpostStatus(state,r.id);return `<article class="panel destination-card" id="destination-${r.id}" tabindex="-1"><span class="kicker">MAPPED GALAXY · ${type?.name||'CORE'}</span><h3>${r.name}</h3><p>${r.desc}</p><p class="galaxy-boost">${type?.desc||'A mapped stellar network.'} ${Object.entries(type?.boost||{}).map(([k,v])=>`+${(v*100).toFixed(1)}% ${k}`).join(' · ')}</p><p>Outpost ${o.level}/10 · ${Object.entries(r.prod||{}).map(([k,v])=>v+' '+k+'/s').join(', ')}</p>${r.id!=='home'?`<p>Next outpost: ${Object.entries(o.cost).map(([k,v])=>format(v)+' '+k).join(' + ')}</p><button class="buy" data-outpost="${r.id}">${o.level>=10?'MAXIMUM LEVEL':'UPGRADE OUTPOST'}</button>`:''}</article>`}).join('');
 const trees=['Navigation','Industry','Ascension'].map(tree=>`<div class="skill-tree"><h3>${tree}</h3>${galaxySkills.filter(n=>n.tree===tree).map(n=>{const x=skillStatus(state,n.id);return `<article class="skill-node ${x.level?'learned':''}"><div><b>${n.name}</b><small>Rank ${x.level}/${n.max} · ${n.desc}</small></div><button class="buy" data-skill="${n.id}" ${x.ok?'':'disabled'}>${x.level>=n.max?'MASTERED':x.label+' · '+format(x.cost)}</button></article>`}).join('')}</div>`).join('');
 return `<div class="section-intro"><p>The map reveals only systems connected to your mapped network. Explore the frontier one step at a time; every galaxy has a type, production profile, and unique boost. Distant galaxies remain outside the signal range.</p><span class="chip">${discovered.length}/${regions.length} GALAXIES MAPPED</span></div><div class="galaxy-summary"><article class="panel"><span class="kicker">VISIBLE FRONTIER</span><strong>${visible.length}</strong><small>signals within range</small></article><article class="panel"><span class="kicker">GALAXY BOOSTS</span><strong>+${(boost.production*100).toFixed(1)}%</strong><small>network production · +${(skill.production*100).toFixed(1)}% skill resonance</small></article><article class="panel frontier-card"><span class="kicker">FRONTIER MASTERY</span><strong>LVL ${frontier.level}</strong><small>Next advance costs ${format(frontier.cost)} knowledge</small><button class="buy" data-frontier ${frontier.ok?'':'disabled'}>ADVANCE FRONTIER</button></article></div><div class="galaxy-map-shell panel"><div class="map-toolbar"><span class="kicker">TACTICAL GALAXY WEB</span><span class="muted">Scroll in every direction · ${discovered.length}/${regions.length} mapped</span></div><div class="galaxy-map-viewport"><div class="galaxy-map"><div class="map-core-label">SOL NETWORK</div><svg viewBox="0 0 2400 2400" aria-hidden="true">${lines}</svg>${nodes}</div></div><div class="galaxy-legend">${galaxyTypes.slice(0,6).map(t=>`<span><i class="type-dot ${t.id}"></i>${t.name}</span>`).join('')}<span>Fog hides distant signals</span></div></div><div class="galaxy-destinations">${cards||'<article class="panel empty-state"><h3>No systems mapped yet</h3><p>Unlock Space Exploration to begin scanning the galaxy web.</p></article>'}</div><section class="skill-web panel"><div class="panel-top"><span class="kicker">GALACTIC SKILL WEB</span><span class="muted">KNOWLEDGE ${format(state.resources.knowledge)} · ${skill.levels} RANKS</span></div><p>Three permanent branches improve navigation, galaxy boosts and outpost production. Each node has 25 ranks with scaling costs.</p><div class="skill-trees">${trees}</div></section>`;
}
function oldGalaxyPage(){
 const skill=skillBonus(state),frontier=frontierStatus(state);
 const map=regions.map(r=>`<button class="region ${state.exploration.regions[r.id]?'discovered':''}" style="left:${r.x}%;top:${r.y}%" data-select-region="${r.id}" aria-label="View ${r.name}"><i></i><b>${r.name}</b><small>${state.exploration.regions[r.id]?'DISCOVERED':'VIEW ROUTE'}</small></button>`).join('');
 const lines=regions.filter(r=>r.parent).map(r=>{const a=regions.find(x=>x.id===r.parent);return `<line x1="${a.x}" y1="${a.y}" x2="${r.x}" y2="${r.y}"/>`}).join('');
 const cards=regions.filter(r=>r.parent).map(r=>{const open=state.exploration.regions[r.id],o=outpostStatus(state,r.id);return `<article class="panel destination-card" id="destination-${r.id}" tabindex="-1"><span class="kicker">VIA ${regions.find(x=>x.id===r.parent).name}</span><h3>${r.name}</h3><p>${r.desc}</p><p>Discovery: ${format(r.cost)} energy · +5% production</p><button class="buy" data-region="${r.id}"></button><p>Outpost ${o.level}/10 · ${Object.entries(r.prod).map(([k,v])=>v+' '+k+'/s').join(', ')}</p>${open?`<p>Next: ${Object.entries(o.cost).map(([k,v])=>format(v)+' '+k).join(' + ')}</p><button class="buy" data-outpost="${r.id}">UPGRADE OUTPOST</button>`:''}</article>`}).join('');
 const trees=['Navigation','Industry','Ascension'].map(tree=>`<div class="skill-tree"><h3>${tree}</h3>${galaxySkills.filter(n=>n.tree===tree).map(n=>{const x=skillStatus(state,n.id);return `<article class="skill-node ${x.level?'learned':''}"><div><b>${n.name}</b><small>Rank ${x.level}/${n.max} · ${n.desc}</small></div><button class="buy" data-skill="${n.id}" ${x.ok?'':'disabled'}>${x.level>=n.max?'MASTERED':x.label+' · '+format(x.cost)}</button></article>`}).join('')}</div>`).join('');
 return `<div class="section-intro"><p>Chart a web of connected galaxies. Discoveries add production, outposts generate rare resources, and the permanent skill web grows through 25 ranks per node. Frontier mastery has no cap.</p><span class="chip">${navigationReady(state)?'NAVIGATION ONLINE':'REQUIRES SPACE EXPLORATION'}</span></div><div class="galaxy-summary"><article class="panel"><span class="kicker">GALAXY WEB</span><strong>${galaxies.length}</strong><small>galaxies · ${Object.keys(state.exploration.regions).length}/${regions.length} systems mapped</small></article><article class="panel"><span class="kicker">SKILL RESONANCE</span><strong>${skill.levels}</strong><small>skill levels · +${(skill.production*100).toFixed(1)}% production</small></article><article class="panel frontier-card"><span class="kicker">FRONTIER MASTERY</span><strong>LVL ${frontier.level}</strong><small>Next advance costs ${format(frontier.cost)} knowledge</small><button class="buy" data-frontier ${frontier.ok?'':'disabled'}>ADVANCE FRONTIER</button></article></div><div class="galaxy panel"><div class="stars"></div><div class="galaxy-labels">${galaxies.map(g=>`<span class="chip ${g.tone}">${g.name}</span>`).join('')}</div><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${lines}</svg>${map}<div class="galaxy-legend">${Object.keys(state.exploration.regions).length}/${regions.length} SYSTEMS · +${(Object.keys(state.exploration.regions).length-1)*5}% PRODUCTION</div></div><div class="galaxy-destinations">${cards}</div><section class="skill-web panel"><div class="panel-top"><span class="kicker">GALACTIC SKILL WEB</span><span class="muted">KNOWLEDGE ${format(state.resources.knowledge)}</span></div><p>Three permanent branches. Each node has 25 ranks, with scaling costs for long-term progression.</p><div class="skill-trees">${trees}</div></section>`;
}
function legacyGalaxyPage(){
 return `<div class="section-intro"><p>Discover connected systems instantly using energy. Each discovery adds 5% production. Build outposts with credits and matter to produce rare resources; each outpost has 10 levels. Discoveries and outposts reset on prestige.</p><span class="chip">${navigationReady(state)?'NAVIGATION ONLINE':'REQUIRES SPACE EXPLORATION'}</span></div>
 <div class="galaxy panel"><div class="stars"></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${regions.filter(r=>r.parent).map(r=>{const a=regions.find(x=>x.id===r.parent);return `<line x1="${a.x}" y1="${a.y}" x2="${r.x}" y2="${r.y}"/>`}).join('')}</svg>
 ${regions.map(r=>`<button class="region ${state.exploration.regions[r.id]?'discovered':''}" style="left:${r.x}%;top:${r.y}%" data-select-region="${r.id}" aria-label="View ${r.name}"><i></i><b>${r.name}</b><small>${state.exploration.regions[r.id]?'DISCOVERED':'VIEW ROUTE'}</small></button>`).join('')}
 <div class="galaxy-legend">${Object.keys(state.exploration.regions).length}/${regions.length} SYSTEMS · +${(Object.keys(state.exploration.regions).length-1)*5}% PRODUCTION</div></div>
 <div class="card-grid galaxy-destinations">${regions.filter(r=>r.parent).map(r=>{const open=state.exploration.regions[r.id],o=outpostStatus(state,r.id);return `<article class="panel" id="destination-${r.id}" tabindex="-1"><span class="kicker">VIA ${regions.find(x=>x.id===r.parent).name}</span><h3>${r.name}</h3><p>${r.desc}</p><p>Discovery: ${format(r.cost)} energy · +5% all production</p><button class="buy" data-region="${r.id}"></button><p>Outpost ${o.level}/10 · base output per level: ${Object.entries(r.prod).map(([key,v])=>v+' '+key+'/s').join(', ')}</p>${open?`<p>${Object.entries(o.cost).map(([key,v])=>format(v)+' '+key).join(' + ')}</p><button class="buy" data-outpost="${r.id}">UPGRADE OUTPOST</button>`:''}</article>`}).join('')}</div>`;
}
function legacyMissionsPage(){return '<div class="mission-grid">'+missions(state).map(m=>`<article class="panel mission"><div><h3>${m.name}</h3><p>${m.desc}</p><div class="progress"><i style="width:${Math.min(100,m.progress/m.goal*100)}%"></i></div><small>${format(m.progress)} / ${format(m.goal)}</small></div><button class="buy" data-claim="${m.id}" ${state.claimed[m.id]||m.progress<m.goal?'disabled':''}>${state.claimed[m.id]?'CLAIMED':'CLAIM +'+m.reward+' SHARDS'}</button></article>`).join('')+'</div>';}
function achievementsPage(){return `<div class="achievement-summary panel"><b>${achievements.filter(a=>achievementProgress(state,a)>=a.goal).length}</b> / ${achievements.length} achievements complete<div class="progress"><i style="width:${achievements.filter(a=>achievementProgress(state,a)>=a.goal).length/achievements.length*100}%"></i></div></div><div class="achievement-grid">${achievements.map(a=>{const p=achievementProgress(state,a),done=p>=a.goal;return `<article class="achievement ${done?'done':''}"><span>${done?'◆':'◇'}</span><div><h3>${a.name}</h3><p>${a.desc}</p><small>${format(Math.min(p,a.goal))} / ${format(a.goal)} · reward +${a.reward} shard</small><button class="buy" data-achievement="${a.id}" ${!done||state.claimed[a.id]?'disabled':''}>${state.claimed[a.id]?'CLAIMED':'CLAIM'}</button></div></article>`}).join('')}</div>`}
function statsPage(){const prod=totalProd(state);return `<div class="stat-grid">${[['Total clicks',format(state.stats.clicks),'clicks'],['Lifetime energy',format(state.stats.totalEnergy),'generated'],['Current output',format(prod.energy||0)+'/s','energy'],['Best combo',format(state.stats.bestCombo),'streak'],['Prestige cycles',state.stats.prestiges,'transcended'],['Time played',format(state.stats.time),'seconds'],['Offline time',format(state.stats.offline),'recovered'],['Buildings',Object.values(state.buildings).reduce((a,b)=>a+b,0),'levels']].map(x=>`<article class="panel stat"><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></article>`).join('')}</div><div class="panel lifetime"><div class="panel-top"><span class="kicker">LIFETIME RESOURCE FLOW</span><span class="muted">ALL-TIME</span></div>${resources.map(r=>`<div class="flow"><span>${r.icon} ${r.name}</span><div class="mini-progress"><i style="width:${Math.min(100,Math.log10((state.resources[r.id]||0)+1)/12*100)}%"></i></div><b>${format(state.resources[r.id]||0)}</b></div>`).join('')}</div>`}
function cosmicPage(){const c=state.cosmic||{},bonus=cosmicBonuses(state),starter=starterChoiceAvailable(state);return `<div class="section-intro"><span class="kicker">ASCENSION ${state.stats.ascensions}</span><h2>${starter?'Choose your first awakening':'Cosmic Knowledge Tree'}</h2><p>${starter?'Your first Ascension grants exactly one affordable starting choice. This choice shapes the civilization era, but later Ascensions open the other branches.':'Permanent knowledge rewrites the rules of the empire. Hidden Transcendence nodes reveal themselves through later Ascensions.'}</p><div class="cosmic-bank">✧ <b>${format(state.resources.knowledge)}</b> cosmic knowledge · ${Object.keys(c.purchased||{}).length} nodes unlocked</div></div>${starter?`<div class="starter-grid">${starterCosmicNodes.map(n=>`<article class="panel starter-node"><span class="kicker">STARTER AWAKENING</span><h3>${n.name}</h3><p>${n.desc}</p><button class="buy" data-cosmic="${n.id}">CHOOSE · 1 KNOWLEDGE</button></article>`).join('')}</div>`:''}<div class="cosmic-summary panel"><b>Permanent effects</b><span>+${(bonus.production*100).toFixed(1)}% production · +${(bonus.research*100).toFixed(1)}% research · +${(bonus.military*100).toFixed(1)}% military</span></div><div class="cosmic-tree">${cosmicBranches.map(b=>`<section class="cosmic-branch ${b.id}"><div class="branch-head"><span class="kicker">${b.name.toUpperCase()}</span><p>${b.desc}</p></div>${cosmicNodes.filter(n=>n.branch===b.id).map(n=>{const x=cosmicStatus(state,n.id),owned=!!c.purchased?.[n.id];return `<article class="cosmic-node ${owned?'owned':''} ${x.hidden?'hidden-node':''}"><div><b>${n.name}</b><small>${x.hidden?'A later Ascension will reveal this node.':n.desc}</small><em>${owned?'PERMANENTLY UNLOCKED':x.label} · ${x.cost?format(x.cost)+' KNOWLEDGE':''}</em></div><button class="buy" data-cosmic="${n.id}" ${x.ok?'':'disabled'}>${owned?'ACTIVE':x.hidden?'HIDDEN':x.label}</button></article>`}).join('')}</section>`).join('')}</div>`}
function civilizationPage(){const c=state.civilization||{},b=civilizationBonuses(state),cols=Object.entries(c.colonies||{});return `<div class="section-intro"><span class="kicker">CIVILIZATION ERA</span><h2>Manage the living empire</h2><p>Colonies specialize into complementary worlds. Specialization creates both output and upkeep, so expansion is a planning decision rather than a flat multiplier.</p></div><div class="stat-grid"><article class="panel stat"><small>POPULATION</small><strong>${format(c.population||0)}</strong><span>growth and housing</span></article><article class="panel stat"><small>CULTURE</small><strong>${format(c.culture||0)}</strong><span>government currency</span></article><article class="panel stat"><small>STABILITY</small><strong>${Math.round((c.stability||0)*100)}%</strong><span>empire stability</span></article><article class="panel stat"><small>ADMIN CAPACITY</small><strong>${format(c.administrativeCapacity||0)}</strong><span>territory support</span></article></div><div class="panel civilization-controls"><span class="kicker">GOVERNMENT</span><p>${c.government?governmentTypes.find(g=>g.id===c.government)?.name:'Choose after the first Ascension'}</p><div class="button-row">${governmentTypes.map(g=>`<button class="secondary" data-government="${g.id}" title="${g.desc}">${g.name}</button>`).join('')}</div></div><div class="colony-grid">${cols.length?cols.map(([id,col])=>`<article class="panel colony-card"><span class="kicker">${col.planet}</span><h3>${col.name}</h3><p>Population ${format(col.population)} · stability ${Math.round((col.stability||1)*100)}%</p><select data-specialize="${id}">${colonySpecializations.map(x=>`<option value="${x.id}" ${col.specialization===x.id?'selected':''}>${x.name}</option>`).join('')}</select><small>${colonySpecializations.find(x=>x.id===col.specialization)?.desc||''}</small></article>`).join(''):'<article class="panel empty-state"><h3>Ascension awakens the first colony</h3><p>Discover connected galaxies, then colonize them from their destination cards.</p></article>'}</div>`}
function diplomacyPage(){const c=state.civilization||{};return `<div class="section-intro"><span class="kicker">GALACTIC POLITICS</span><h2>Diplomacy</h2><p>Relationships respond to contact, trade, expansion, treaties, rivalry, and war. Build trust or compete for strategic space.</p></div><div class="diplomacy-grid">${civList(state).map(x=>{const rel=c.relations?.[x.id]||0;return `<article class="panel civ-card"><span class="kicker">${x.personality.toUpperCase()} · ${x.species}</span><h3>${x.name}</h3><p>${x.government} · technology ${x.technology} · military ${format(x.military)}</p><strong class="relation ${rel<0?'negative':''}">${rel>55?'ALLIED':rel>25?'FRIENDLY':rel>-10?'NEUTRAL':rel>-45?'SUSPICIOUS':'HOSTILE'} · ${rel}</strong><div class="button-row"><button class="secondary" data-diplomacy="contact:${x.id}">CONTACT</button><button class="secondary" data-diplomacy="improve:${x.id}">IMPROVE</button><button class="secondary" data-diplomacy="trade:${x.id}">TRADE PACT</button><button class="danger" data-diplomacy="war:${x.id}">DECLARE WAR</button></div></article>`}).join('')}</div>`}
function tradePage(){const c=state.civilization||{},mapped=Object.keys(state.exploration.regions);return `<div class="section-intro"><span class="kicker">INTERSTELLAR ECONOMY</span><h2>Trade networks</h2><p>Trade routes convert diplomatic trust and connected territory into reliable credit flow. Distance and capacity matter as the network expands.</p><div class="cosmic-bank">TRADE CAPACITY <b>${format(c.tradeCapacity||0)}</b> · ACTIVE ROUTES <b>${c.tradeRoutes?.length||0}</b></div></div><div class="panel trade-list">${(c.tradeRoutes||[]).map(r=>`<div class="trade-row"><b>${civList(state).find(x=>x.id===r.civId)?.name||r.civId}</b><span>via ${r.regionId}</span><strong>+${format(25*r.efficiency)} credits/s</strong></div>`).join('')||'<div class="empty-state"><h3>No routes established</h3><p>Use a mapped system below to open your first galactic route.</p></div>'}</div><div class="panel trade-list"><span class="kicker">AVAILABLE CHARTERS</span>${civList(state).slice(0,5).map(x=>`<div class="trade-row"><b>${x.name}</b><span>${x.personality} civilization</span><select data-trade-civ="${x.id}">${mapped.map(id=>`<option value="${id}">${id}</option>`).join('')}</select><button class="buy" data-trade="${x.id}:${mapped[0]||'home'}">ESTABLISH · 250 ₡</button></div>`).join('')}</div><div class="panel policy-panel"><span class="kicker">POLICIES</span><div class="policy-grid">${policyCards.map(p=>`<article class="policy-card ${c.policies?.includes(p.id)?'active':''}"><h3>${p.name}</h3><small>${p.cat}</small><p>${p.desc}</p><button class="buy" data-policy="${p.id}">${c.policies?.includes(p.id)?'REMOVE':'ADOPT'}</button></article>`).join('')}</div></div>`}
function fleetsPage(){const c=state.civilization||{};return `<div class="section-intro"><span class="kicker">STRATEGIC DEFENSE</span><h2>Fleets and logistics</h2><p>War is a strategic simulation: fleets need matter to build, supply to operate, and enough strength to achieve objectives.</p><div class="cosmic-bank">MILITARY POWER <b>${format(militaryPower(state))}</b> · FLEET CAPACITY ${format(Object.values(c.fleets||{}).reduce((a,b)=>a+b,0))}</div></div><div class="fleet-grid">${shipClasses.map(x=>`<article class="panel ship-card"><span class="kicker">SHIP CLASS</span><h3>${x.name}</h3><p>Hull ${x.hull} · Firepower ${x.firepower} · Supply ${x.supply}</p><small>Cost ${x.cost} matter · owned ${c.fleets?.[x.id]||0}</small><button class="buy" data-fleet="${x.id}">BUILD ONE</button></article>`).join('')}</div><div class="panel war-list"><span class="kicker">ACTIVE WARS</span>${(c.wars||[]).map(w=>`<div class="trade-row"><b>${civList(state).find(x=>x.id===w.civId)?.name||w.civId}</b><span>${w.objective} · exhaustion ${Math.round((w.exhaustion||0)*100)}%</span><button class="buy" data-warresolve="${w.civId}">RESOLVE BATTLE</button></div>`).join('')||'<p class="muted">No active wars. Diplomacy can prevent conflicts—or start them.</p>'}</div>`}
function megaPage(){const c=state.civilization||{};return `<div class="section-intro"><span class="kicker">GREAT PROJECTS</span><h2>Megastructures</h2><p>These are multi-stage civilization projects. Every completed stage provides a milestone and increases the cost of the next stage.</p></div><div class="mega-grid">${megaProjects.map(m=>{const stage=c.megastructures?.[m.id]||0,scale=Math.pow(3,stage);return `<article class="panel mega-card"><span class="kicker">STAGE ${stage}/${m.stages}</span><h3>${m.name}</h3><p>${m.desc}</p><div class="progress"><i style="width:${stage/m.stages*100}%"></i></div><small>Next stage: ${Object.entries(m.cost).map(([r,v])=>format(v*scale)+' '+r).join(' · ')}</small><button class="buy" data-mega="${m.id}" ${stage>=m.stages?'disabled':''}>${stage>=m.stages?'COMPLETED':'BUILD STAGE '+(stage+1)}</button></article>`}).join('')}</div>`}
function settingsPage(){return `<div class="settings-grid"><article class="panel"><span class="kicker">SAVE CONTROL</span><h2>Local vault</h2><p>Your save is stored in this browser and autosaves every 10 seconds. Export a backup before clearing browser data.</p><div class="button-row"><button class="buy" data-action="save">SAVE NOW</button><button class="secondary" data-action="export">EXPORT</button><label class="secondary file">IMPORT<input type="file" id="import" accept=".json"/></label></div><button class="danger" data-action="reset">RESET ALL PROGRESS</button></article><article class="panel"><span class="kicker">TRANSCENDENCE</span><h2>Prestige chamber</h2><p>Reset normal resources and buildings. Keep upgrades, research, achievements, lifetime statistics and prestige currencies.</p><div class="prestige-reward">✦ <b>${format(Math.floor(Math.sqrt(Math.max(0,state.resources.energy)/1e6)))}</b> shards available</div><button class="buy" data-action="prestige">TRANSCEND</button><hr/><span class="kicker">SECOND LAYER</span><h3>Ascension</h3><p>Requires Galactic Infrastructure and 100 prestige shards. Resets shards for cosmic knowledge and unlocks civilization systems.</p><button class="buy" data-action="ascend">ASCEND</button></article></div>`}
function upgradePageFixed(){return `<div class="section-intro"><p>Install permanent protocols. Clicking upgrades increase the reactor's direct energy output and unlock in a clear chain.</p></div><div class="upgrade-grid">${upgrades.map(u=>{const got=state.upgrades[u.id],reqOk=!u.req||u.req.every(id=>state.upgrades[id]),can=reqOk&&Object.entries(u.cost).every(([r,c])=>(state.resources[r]||0)>=c);const req=u.req?.map(id=>upgrades.find(x=>x.id===id)?.name||id).join(', ');return `<article class="upgrade ${got?'owned':''} ${reqOk?'':'upgrade-locked'}"><div class="upgrade-top"><span class="upgrade-cat">${u.cat}</span>${got?'<span class="owned-mark">INSTALLED</span>':''}</div><h3>${u.name}</h3><p>${u.desc}</p>${req?`<small class="upgrade-requirement">Requires: ${req}</small>`:''}<div class="cost">${Object.entries(u.cost).map(([r,c])=>`<span>${format(c)} ${r}</span>`).join('')}</div><button class="buy" data-upgrade="${u.id}" ${got||!can?'disabled':''}>${got?'ACTIVE':!reqOk?'LOCKED':can?'INSTALL':'INSUFFICIENT'}</button></article>`}).join('')}</div>`}
upgradePage=upgradePageFixed;
function totalMult(){const skill=skillBonus(state),galaxy=galaxyBoosts(state);return (1+(state.upgrades.reactors?.value||0)+(state.research.industrial?.value||0)+(state.research.efficiency?.value||0)+(state.upgrades.singularity?.value||0))*(1+Math.sqrt(state.resources.shards)*.1+state.resources.knowledge*.5)*(1+(Object.keys(state.exploration.regions).length-1)*.05)*(1+Math.floor(state.buildings.fusion/10)*.05)*(1+skill.production+skill.frontier+galaxy.production)*(state.boost>0?2:1)}
function render(){const pages={command,buildings:buildingPage,upgrades:upgradePage,research:researchPage,galaxy:galaxyPage,missions:missionsPage,achievements:achievementsPage,stats:statsPage,settings:settingsPage,civilization:civilizationPage,diplomacy:diplomacyPage,trade:tradePage,fleets:fleetsPage,cosmic:cosmicPage,megastructures:megaPage};if(!pages[view]||state.stats.ascensions<1&&expansionNav.some(x=>x[0]===view))view='command';app.innerHTML=layout(pages[view]());document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>{view=x.dataset.view;render()});bind();refreshGalaxy();document.querySelectorAll('[data-buyqty]').forEach(x=>x.classList.toggle('active',x.dataset.buyqty===buyQuantity));if(toastMessage){const t=document.querySelector('#toast');t.textContent=toastMessage;t.classList.add('show');}}
function notify(msg){toastMessage=msg;const t=document.querySelector('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>{toastMessage='';document.querySelector('#toast')?.classList.remove('show')},2600)}
function spawnClickFx(e,result){const reactor=document.querySelector('.reactor');if(!reactor||matchMedia('(prefers-reduced-motion: reduce)').matches)return;if(reactor.querySelectorAll('.particle').length>60)return;const rect=reactor.getBoundingClientRect(),core=document.querySelector('#core').getBoundingClientRect(),x=(e.detail?e.clientX:core.left+core.width/2)-rect.left,y=(e.detail?e.clientY:core.top+core.height/2)-rect.top;const gain=document.createElement('span');gain.className=`float-text ${result.crit?'critical':''}`;gain.textContent=`+${format(result.amount)}${result.crit?' CRIT':''}`;gain.style.left=`${x}px`;gain.style.top=`${y}px`;reactor.append(gain);setTimeout(()=>gain.remove(),900);if(state.settings.particles!==false){for(let i=0;i<(result.crit?12:7);i++){const p=document.createElement('i');p.className='particle';p.style.left=`${x}px`;p.style.top=`${y}px`;p.style.setProperty('--dx',`${Math.cos(i/7*Math.PI*2)*(35+Math.random()*45)}px`);p.style.setProperty('--dy',`${Math.sin(i/7*Math.PI*2)*(35+Math.random()*45)}px`);reactor.append(p);setTimeout(()=>p.remove(),700)}}}
function bind(){document.querySelectorAll('[data-select-region]').forEach(btn=>btn.onclick=()=>{const card=document.getElementById('destination-'+btn.dataset.selectRegion);if(card){card.scrollIntoView({block:'center',behavior:'auto'});card.focus({preventScroll:true})}else notify('Sol is your home system')});document.querySelectorAll('[data-outpost]').forEach(btn=>btn.onclick=()=>{notify(upgradeOutpost(state,btn.dataset.outpost)?'Outpost upgraded':'More credits and matter required');save(state);render()});document.querySelectorAll('[data-claim]').forEach(x=>x.onclick=()=>{claimMission(state,x.dataset.claim);save(state);render()});document.querySelectorAll('[data-achievement]').forEach(x=>x.onclick=()=>{claimAchievement(state,x.dataset.achievement);save(state);render()});document.querySelectorAll('[data-region]').forEach(x=>x.onclick=()=>{notify(discover(state,x.dataset.region)?'System discovered: +5% production':discoveryStatus(state,x.dataset.region).label);save(state);render()});document.querySelectorAll('#core').forEach(x=>x.addEventListener('click',e=>{e.preventDefault();const r=click(state);notify(r.crit?'CRITICAL ENERGY SURGE':'Energy generated');x.classList.remove('pulse');void x.offsetWidth;x.classList.add('pulse');spawnClickFx(e,r);refreshHUD()}));document.querySelectorAll('[data-buy]').forEach(x=>x.onclick=()=>{let raw=document.querySelector('.buy-toggle .active')?.dataset.buyqty||'1';let q=raw==='max'?9999:Number(raw);const n=buy(state,x.dataset.buy,q);notify(n?`${x.textContent==='BUILD'?'Constructed':'Upgraded'} ${n} level${n>1?'s':''}`:'Need more credits');render()});document.querySelectorAll('[data-upgrade]').forEach(x=>x.onclick=()=>{notify(buyUpgrade(state,x.dataset.upgrade)?'Protocol installed':'Cannot install protocol');render()});document.querySelectorAll('[data-research]').forEach(x=>x.onclick=()=>{notify(buyResearch(state,x.dataset.research)?'Research node completed':'Prerequisites or research missing');render()});document.querySelectorAll('[data-action]').forEach(x=>x.onclick=()=>action(x.dataset.action));document.querySelectorAll('[data-buyqty]').forEach(x=>x.onclick=()=>{document.querySelectorAll('[data-buyqty]').forEach(y=>y.classList.remove('active'));x.classList.add('active');buyQuantity=x.dataset.buyqty});const inp=document.querySelector('#import');if(inp)inp.onchange=()=>{const f=inp.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const p=JSON.parse(rd.result);if(!p.resources||!p.buildings)throw 0;state=normalize(p);save(state);notify('Save imported safely');render()}catch{notify('Import rejected: invalid save file')}};rd.readAsText(f)}}
function action(a){if(a==='convert'){notify(convertEnergy(state)?'Energy sold for credits':'Need at least 10 energy');render()}if(a==='save'){notify(save(state)?'Progress saved to local vault':'Storage unavailable — export your save')}if(a==='export'){const blob=new Blob([JSON.stringify(state)],{type:'application/json'}),url=URL.createObjectURL(blob),el=document.createElement('a');el.href=url;el.download='starforge-save.json';el.click();URL.revokeObjectURL(url);notify('Backup exported')}if(a==='boost'){if(state.boostCooldown>0){notify('Boost recharges in '+Math.ceil(state.boostCooldown)+' seconds');return}state.boost=60;state.boostCooldown=300;notify('Production boost active for 60 seconds');render()}if(a==='prestige'){if(confirm('Transcend? Normal progress will reset. Shards, achievements, and selected research are retained.')){notify(prestige(state)?'Transcendence complete':'Reach 1,000,000 energy first');render()}}if(a==='ascend'){if(confirm('Ascend? Your normal empire and prestige shards reset. Research, achievements, exploration skills and Cosmic Knowledge remain.')){notify(ascend(state)?'Ascension complete — choose one Cosmic awakening':'Requires Galactic Infrastructure and 100 shards');render()}}if(a==='reset'&&confirm('Delete all local progress? This cannot be undone.')){storage.removeItem('starforge-save');storage.removeItem('starforge-last');state=load();notify('Vault cleared');render()}}
document.addEventListener('change',e=>{const select=e.target.closest('[data-specialize]');if(select){notify(specializeColony(state,select.dataset.specialize,select.value)?'Colony specialization updated':'Unable to specialize colony');save(state);render();return}const tradeSelect=e.target.closest('[data-trade-civ]');if(tradeSelect){const button=tradeSelect.closest('.trade-row')?.querySelector('[data-trade]');if(button)button.dataset.trade=`${tradeSelect.dataset.tradeCiv}:${tradeSelect.value}`;}});
document.addEventListener('click',e=>{const cosmic=e.target.closest('[data-cosmic]');if(cosmic){notify(chooseStarter(state,cosmic.dataset.cosmic)||buyCosmic(state,cosmic.dataset.cosmic)?'Cosmic Knowledge node unlocked':'Requirements not met or starter choice already made');save(state);render();return}const gov=e.target.closest('[data-government]');if(gov){notify(setGovernment(state,gov.dataset.government)?'Government adopted':'Need 25 culture or civilization is locked');save(state);render();return}const policy=e.target.closest('[data-policy]');if(policy){notify(togglePolicy(state,policy.dataset.policy)?'Policy updated':'Policy slots are full');save(state);render();return}const dip=e.target.closest('[data-diplomacy]');if(dip){const [actionName,id]=dip.dataset.diplomacy.split(':');notify(diplomacyAction(state,id,actionName)?'Diplomatic position updated':'Diplomatic action unavailable');save(state);render();return}const fleet=e.target.closest('[data-fleet]');if(fleet){notify(buildFleet(state,fleet.dataset.fleet)?'Fleet unit constructed':'Need more matter');save(state);render();return}const resolve=e.target.closest('[data-warresolve]');if(resolve){notify(resolveWar(state,resolve.dataset.warresolve)?'Battle resolved in your favor':'Battle requires more fleet power');save(state);render();return}const mega=e.target.closest('[data-mega]');if(mega){notify(buildMega(state,mega.dataset.mega)?'Megastructure stage completed':'Required resources missing');save(state);render();return}const trade=e.target.closest('[data-trade]');if(trade){const [civ,region]=trade.dataset.trade.split(':');notify(establishTrade(state,civ,region)?'Trade route established':'Trade route unavailable');save(state);render();return}});
document.addEventListener('click',e=>{const skill=e.target.closest('[data-skill]');if(skill){notify(upgradeSkill(state,skill.dataset.skill)?'Skill rank increased':'Prerequisites or knowledge missing');save(state);render();return}const frontier=e.target.closest('[data-frontier]');if(frontier){notify(advanceFrontier(state)?'Frontier advanced: +1% production':'Need more cosmic knowledge');save(state);render()}});
document.addEventListener('click',e=>{const node=e.target.closest('[data-select-region]');if(node&&!document.getElementById('destination-'+node.dataset.selectRegion)){const r=regions.find(x=>x.id===node.dataset.selectRegion);if(r&&!state.exploration.regions[r.id])notify('Signal detected: map the connected frontier to reveal '+r.name)}});
document.addEventListener('click',e=>{const opportunity=e.target.closest('[data-opportunity]');if(opportunity){notify(startOpportunity(state,opportunity.dataset.opportunity)?'Opportunity active':'Opportunity is recharging');save(state);render();return}});
function frontierDestinationMarkup(){
 const host=document.querySelector('.galaxy-destinations');
 if(!host||host.querySelector('.frontier-destination'))return;
 const visible=regions.filter(r=>isGalaxyVisible(state,r)&&!state.exploration.regions[r.id]);
 host.insertAdjacentHTML('afterbegin',visible.map(r=>{const status=discoveryStatus(state,r.id),parent=regions.find(x=>x.id===r.parent),type=galaxyTypes.find(t=>t.id===r.type);return `<article class="panel destination-card frontier-destination" id="destination-${r.id}" tabindex="-1"><span class="kicker">NEXT FRONTIER · VIA ${parent?.name||'UNKNOWN'}</span><h3>${r.name}</h3><p>${r.desc}</p><p class="galaxy-boost">${type?.desc||'A new signal is within range.'}</p><p>Discovery cost: <b>${format(r.cost)} energy</b>${r.tech?` · Requires ${r.tech}`:''}</p><button class="buy" data-region="${r.id}" ${status.ok?'':'disabled'}>${status.label}</button></article>`}).join(''));
}
function centerGalaxyMap(){const viewport=document.querySelector('.galaxy-map-viewport');if(!viewport)return;requestAnimationFrame(()=>{viewport.scrollLeft=Math.max(0,(viewport.scrollWidth-viewport.clientWidth)/2);viewport.scrollTop=Math.max(0,(viewport.scrollHeight-viewport.clientHeight)/2);});}
new MutationObserver(()=>{frontierDestinationMarkup();centerGalaxyMap();}).observe(app,{childList:true,subtree:true});
document.addEventListener('click',e=>{const region=e.target.closest('[data-region]');if(region){const ok=discover(state,region.dataset.region);notify(ok?'Galaxy discovered — frontier expanded':'Cannot discover yet: '+discoveryStatus(state,region.dataset.region).label);save(state);render();}});
function clickPower(){return 1+(state.buildings?.clicking||0)+Object.values(state.upgrades).filter(u=>u?.effect==='clickFlat').reduce((sum,u)=>sum+Math.max(0,Number(u.value)||0),0)}
function refreshGalaxy(){
 document.querySelectorAll('[data-region]').forEach(btn=>{const status=discoveryStatus(state,btn.dataset.region);btn.disabled=!status.ok;btn.textContent=status.label;});
 document.querySelectorAll('[data-outpost]').forEach(btn=>{const status=outpostStatus(state,btn.dataset.outpost);btn.disabled=!status.ok;btn.textContent=status.level>=10?'MAXIMUM LEVEL':status.ok?'UPGRADE OUTPOST':'NEEDS CREDITS / MATTER';});
}
function refreshHUD(){
 refreshGalaxy();
 const prod=totalProd(state);
 const clickLabel=document.querySelector('#core small');if(clickLabel)clickLabel.textContent='+'+format(clickPower())+' ENERGY';
 document.querySelectorAll('[data-claim]').forEach(btn=>{
 const mission=missions(state).find(m=>m.id===btn.dataset.claim),card=btn.closest('article');
 btn.disabled=!!state.claimed[mission.id]||mission.progress<mission.goal;
 card.querySelector('small').textContent=format(mission.progress)+' / '+format(mission.goal);
 card.querySelector('.progress i').style.width=Math.min(100,mission.progress/mission.goal*100)+'%';
 });
 document.querySelectorAll('[data-upgrade]').forEach(btn=>{const u=upgrades.find(u=>u.id===btn.dataset.upgrade);btn.disabled=!!state.upgrades[u.id]||!Object.entries(u.cost).every(([r,c])=>state.resources[r]>=c);btn.textContent=state.upgrades[u.id]?'ACTIVE':btn.disabled?'INSUFFICIENT':'INSTALL';});
 document.querySelectorAll('[data-upgrade]').forEach(btn=>{const u=upgrades.find(x=>x.id===btn.dataset.upgrade),reqOk=!u.req||u.req.every(id=>state.upgrades[id]);if(!reqOk){btn.disabled=true;btn.textContent='LOCKED'}});
 document.querySelectorAll('[data-buy]').forEach(btn=>{const b=buildings.find(b=>b.id===btn.dataset.buy);const unlocked=Math.max(state.stats.totalEnergy,state.resources.energy)>=b.unlock;btn.disabled=!unlocked||state.resources.credits<cost(b,state.buildings[b.id]);btn.textContent=unlocked?'BUILD':'LOCKED';});
 document.querySelectorAll('.production-row strong').forEach((el,i)=>el.textContent='+'+format(prod[resources[i].id]||0)+'/s');
 const badge=document.querySelector('.badge');if(badge)badge.textContent=missions(state).filter(m=>!state.claimed[m.id]&&m.progress>=m.goal).length;

 document.querySelectorAll('.resource b').forEach((el,i)=>el.textContent=format(state.resources[resources[i].id]||0));
 const combo=document.querySelector('.combo>b');if(combo)combo.textContent=state.combo;
 const meter=document.querySelector('.combo-meter i');if(meter)meter.style.width=Math.min(100,state.combo*2)+'%';
 const metrics=document.querySelectorAll('.metrics strong');if(metrics.length){metrics[0].textContent=format(state.resources.energy);metrics[1].textContent=format(state.stats.clicks);metrics[2].textContent=(totalMult()*100).toFixed(0)+'%';}
}
function missionRewardText(m){return typeof m.reward==='number'?`+${m.reward} shards`:Object.entries(m.reward||{}).map(([key,value])=>`+${format(value)} ${key}`).join(' · ')}
function missionsPage(){return `<div class="mission-guide"><span class="kicker">TUTORIAL ROUTE</span><p>Complete each directive in order. Rewards are paid immediately and the next objective unlocks automatically.</p></div><div class="mission-grid">${missions(state).map(m=>`<article class="panel mission ${m.locked?'locked':''}"><div><span class="mission-step">${m.id.startsWith('tutorial-')?'TUTORIAL':'MISSION'}</span><h3>${m.name}</h3><p>${m.desc}</p>${m.tip?`<small class="mission-tip">${m.tip}</small>`:''}<div class="progress"><i style="width:${Math.min(100,m.progress/m.goal*100)}%"></i></div><small>${m.locked?'LOCKED · COMPLETE THE PREVIOUS DIRECTIVE':format(m.progress)+' / '+format(m.goal)}</small></div><button class="buy" data-claim="${m.id}" ${m.locked||state.claimed[m.id]||m.progress<m.goal?'disabled':''}>${state.claimed[m.id]?'CLAIMED':m.locked?'LOCKED':'CLAIM '+missionRewardText(m)}</button></article>`).join('')}</div>`}
const recovery=offline(state);render();if(recovery)notify('Recovered '+format(recovery.energy)+' energy while away');
let last=Date.now(),saved=last;
setInterval(()=>{
 const now=Date.now();if(document.hidden)return;
 tick(state,Math.max(0,Math.min((now-last)/1000,60)));last=now;
 refreshHUD();
 
 if(now-saved>=10000){save(state);saved=now}
},250);
document.addEventListener('visibilitychange',()=>{if(document.hidden){save(state)}else{offline(state);last=Date.now();render()}});
window.addEventListener('pagehide',()=>save(state));
document.addEventListener('keydown',e=>{if(!e.repeat&&e.code==='Space'&&view==='command'&&!/BUTTON|INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)){e.preventDefault();document.querySelector('#core')?.click()}});
