import {regions} from '../data/gameData.js';
import {planetTypes,colonySpecializations,governmentTypes,policyCards,strategicResources,shipClasses,megaProjects} from '../data/cosmicData.js';

const civNames=['Auralis Compact','Veyr Collective','Helion League','Nexari Continuum','Orinth Assembly','Keth Foundries','Lumen Accord','Sable Machines','Tirian Exchange','Eclipse Court'];
const personalities=['Scientific','Mercantile','Expansionist','Cooperative','Industrial','Isolationist','Militaristic','Machine'];
const hash=s=>{let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0};
const pick=(a,n)=>a[n%a.length];
export function defaultCivilization(){return {unlocked:false,population:0,housing:0,employment:0,happiness:1,stability:1,education:0,culture:0,food:0,administrativeCapacity:0,government:null,policies:[],colonies:{},civilians:generateCivilizations(),relations:{},tradeRoutes:[],tradeCapacity:0,territory:{},fleets:{},wars:[],events:[],anomalies:[],strategic:Object.fromEntries(strategicResources.map(x=>[x,0])),megastructures:{},era:0,lastUpdate:0};}
export function generateCivilizations(){return civNames.map((name,i)=>({id:`civ-${i}`,name,species:['Human-descended','Silicon collective','Crystal minds','Gas-born','Synthetic','Oceanic'][i%6],government:['Federation','Directorate','Collective','Commonwealth','Machine Council'][i%5],personality:pick(personalities,hash(name)%personalities.length),territory:[],technology:1+i%5,military:20+i*18,economy:50+i*35,attitude:'Unknown',goals:['expand','research','trade','defend'][i%4],trust:0}));}
export function ensureCivilization(s){if(!s.civilization||typeof s.civilization!=='object')s.civilization=defaultCivilization();const c=s.civilization;for(const key of ['colonies','relations','fleets','territory','megastructures'])c[key]??={};c.policies??=[];c.tradeRoutes??=[];c.wars??=[];c.events??=[];c.anomalies??=[];c.strategic??={};for(const r of strategicResources)c.strategic[r]??=0;c.government??=null;c.unlocked=!!(c.unlocked||s.stats.ascensions>0);return c;}
export function migrateCivilization(s){const c=ensureCivilization(s);if(c.unlocked&&!Object.keys(c.colonies).length){c.colonies={home:{name:'Sol Capital',planet:'Terran',specialization:'administrative',population:10,housing:20,stability:1}};c.population=10;c.housing=20;c.administrativeCapacity=10;c.territory.home='player';}return c;}
export function civilizationUnlock(s){return s.stats.ascensions>0||!!s.cosmic?.firstChoice;}
export function colonyList(s){return Object.values(ensureCivilization(s).colonies);}
export function colonyStatus(s,id){const c=ensureCivilization(s),col=c.colonies[id];if(!col)return {ok:false,label:'Colony not found'};const spec=colonySpecializations.find(x=>x.id===col.specialization);return {ok:true,colony:col,specialization:spec};}
export function colonize(s,regionId){const c=ensureCivilization(s);if(!civilizationUnlock(s)||c.colonies[regionId]||!s.exploration.regions[regionId])return false;const r=regions.find(x=>x.id===regionId);if(!r)return false;const cost=Math.ceil(Math.max(1000,r.cost*.02));if(s.resources.credits<cost)return false;s.resources.credits-=cost;c.colonies[regionId]={name:`${r.name} Colony`,planet:pick(planetTypes,hash(regionId)%planetTypes.length),specialization:'industrial',population:1,housing:5,stability:1};c.territory[regionId]='player';c.population+=1;c.housing+=5;return true;}
export function specializeColony(s,id,specialization){const col=ensureCivilization(s).colonies[id],spec=colonySpecializations.find(x=>x.id===specialization);if(!col||!spec)return false;col.specialization=specialization;return true;}
export function setGovernment(s,id){const c=ensureCivilization(s),g=governmentTypes.find(x=>x.id===id);if(!g||!c.unlocked||s.resources.culture<25)return false;s.resources.culture-=25;c.government=id;return true;}
export function togglePolicy(s,id){const c=ensureCivilization(s),p=policyCards.find(x=>x.id===id);if(!p||!c.unlocked)return false;const i=c.policies.indexOf(id);if(i>=0){c.policies.splice(i,1);return true;}if(c.policies.length>=3)return false;c.policies.push(id);return true;}
export function civilizationBonuses(s){const c=ensureCivilization(s),out={population:0,industry:0,research:0,energyDemand:0,military:0,trade:0,culture:0,capacity:0,stability:0,growth:0,credits:0,automation:0,supply:0,diplomacy:0,happiness:0};const add=x=>Object.entries(x||{}).forEach(([k,v])=>out[k]=(out[k]||0)+v);if(c.government)add(governmentTypes.find(g=>g.id===c.government)?.effects);for(const id of c.policies)add(policyCards.find(p=>p.id===id)?.effects);for(const col of Object.values(c.colonies))add(colonySpecializations.find(x=>x.id===col.specialization)?.effects);return out;}
export function civilizationTick(s,dt){const c=ensureCivilization(s);if(!civilizationUnlock(s))return;const b=civilizationBonuses(s),colonies=Object.values(c.colonies);const growth=Math.max(0,.01*(1+(b.growth||0))*(1+(s.resources.energy>0?.1:0)));c.population=Math.min(1e100,c.population+colonies.length*growth*dt);c.culture=Math.max(0,(c.culture||0)+colonies.length*.01*(1+(b.culture||0))*dt);c.happiness=Math.max(0,Math.min(2,1+(b.happiness||0)-(b.energyDemand||0)*.12));c.stability=Math.max(0,Math.min(2,1+(b.stability||0)));c.administrativeCapacity=Math.max(10,colonies.length*10*(1+(b.capacity||0)));for(const col of colonies){col.population=Math.max(0,(col.population||1)+growth*dt/Math.max(1,colonies.length));col.housing=Math.max(5,col.housing||5);}c.employment=Math.min(c.population,c.population*.72);}
export function diplomacyAction(s,civId,action){const c=ensureCivilization(s),civ=c.civilizations?.find(x=>x.id===civId)||civList(s).find(x=>x.id===civId);if(!civ)return false;const relation=c.relations[civId]??0;const cost=action==='improve'?Math.ceil(100+Math.max(0,-relation)*20):0;if(cost&&s.resources.credits<cost)return false;if(cost)s.resources.credits-=cost;const delta={contact:3,improve:12,trade:8,pact:5,alliance:15,rivalry:-20,war:-50,peace:20}[action]||0;c.relations[civId]=Math.max(-100,Math.min(100,relation+delta));civ.attitude=c.relations[civId]>55?'Allied':c.relations[civId]>25?'Friendly':c.relations[civId]>-10?'Neutral':c.relations[civId]>-45?'Suspicious':'Hostile';if(action==='war'&&!c.wars.some(w=>w.civId===civId))c.wars.push({civId,objective:'Claim territory',progress:0,exhaustion:0});if(action==='peace')c.wars=c.wars.filter(w=>w.civId!==civId);return true;}
export function civList(s){const c=ensureCivilization(s);return c.civilizations??(c.civilizations=generateCivilizations());}
export function establishTrade(s,civId,regionId){const c=ensureCivilization(s),civ=civList(s).find(x=>x.id===civId);if(!civ||!c.colonies?.[regionId]&& !s.exploration.regions[regionId])return false;if(c.tradeRoutes.some(r=>r.civId===civId&&r.regionId===regionId))return false;const cost=250;if(s.resources.credits<cost)return false;s.resources.credits-=cost;c.tradeRoutes.push({civId,regionId,efficiency:1,distance:1});c.tradeCapacity+=10;return true;}
export function buildFleet(s,shipId,amount=1){const c=ensureCivilization(s),ship=shipClasses.find(x=>x.id===shipId);amount=Math.max(1,Math.min(100,Math.floor(amount)));if(!ship||!c.unlocked||s.resources.matter<ship.cost*amount)return false;s.resources.matter-=ship.cost*amount;c.fleets[shipId]=(c.fleets[shipId]||0)+amount;return true;}
export function militaryPower(s){const c=ensureCivilization(s);return Object.entries(c.fleets).reduce((n,[id,count])=>n+(shipClasses.find(x=>x.id===id)?.firepower||0)*count,0)*(1+(civilizationBonuses(s).military||0));}
export function resolveWar(s,civId){const c=ensureCivilization(s),civ=civList(s).find(x=>x.id===civId),power=militaryPower(s);if(!civ||!c.wars.some(w=>w.civId===civId)||power<=0)return false;const result=power>=civ.military;if(result){civ.military=Math.max(0,Math.floor(civ.military*.85));c.relations[civId]=Math.max(-100,(c.relations[civId]||-50)+8);c.wars=c.wars.filter(w=>w.civId!==civId);s.resources.credits+=Math.ceil(civ.military*4);}else{c.wars=c.wars.map(w=>w.civId===civId?{...w,exhaustion:(w.exhaustion||0)+.2}:w);}return result;}
export function buildMega(s,id){const c=ensureCivilization(s),m=megaProjects.find(x=>x.id===id),stage=c.megastructures[id]||0;if(!m||stage>=m.stages||!c.unlocked)return false;const scale=Math.pow(3,stage);for(const [r,v] of Object.entries(m.cost))if((s.resources[r]||0)<v*scale)return false;for(const [r,v] of Object.entries(m.cost))s.resources[r]-=v*scale;c.megastructures[id]=stage+1;return true;}
export function eventTick(s){const c=ensureCivilization(s);if(!c.unlocked||Math.random()>0.012)return null;const types=[['Scientific discovery', 'research',250],['Economic boom','credits',500],['Colony festival','culture',20],['Ancient signal','knowledge',1],['Resource shortage','energy',-200]];const e=types[Math.floor(Math.random()*types.length)];s.resources[e[1]]=Math.max(0,(s.resources[e[1]]||0)+e[2]);const entry=`EVENT — ${e[0]}: ${e[2]>=0?'+':''}${e[2]} ${e[1]}`;c.events.unshift({name:e[0],at:Date.now()});s.log.unshift(entry);s.log=s.log.slice(0,50);return entry;}
export {colonySpecializations,governmentTypes,policyCards,shipClasses,megaProjects,strategicResources};
