import {cosmicNodes,cosmicBranches,starterCosmicNodes} from '../data/cosmicData.js';
export function cosmicState(){return {unlocked:false,firstChoice:null,purchased:{},ascensionMilestones:0,era:0,realityFragments:0};}
export function ensureCosmic(s){s.cosmic??=cosmicState();s.cosmic.purchased??={};s.cosmic.ascensionMilestones??=s.stats.ascensions||0;s.cosmic.unlocked=!!(s.cosmic.unlocked||s.stats.ascensions>0);return s.cosmic;}
export function cosmicLevel(s,id){return Math.max(0,Math.floor(ensureCosmic(s).purchased[id]||0));}
export function cosmicStatus(s,id){const node=cosmicNodes.find(n=>n.id===id),c=ensureCosmic(s);if(!node)return {ok:false,label:'Unknown node'};if(node.hidden&&!c.purchased[id]&&s.stats.ascensions<3)return {ok:false,label:'Hidden until Ascension III',hidden:true};const level=cosmicLevel(s,id);if(level>=1)return {ok:false,label:'UNLOCKED',level,cost:0};if(node.starter&&c.firstChoice&&c.firstChoice!==id&&s.stats.ascensions<2)return {ok:false,label:'Available after Ascension II',level,cost:node.cost};if(!node.starter&&!c.firstChoice)return {ok:false,label:'Choose a starter first',level,cost:node.cost};if(node.req.some(req=>!c.purchased[req]))return {ok:false,label:'Requires '+node.req.map(req=>cosmicNodes.find(n=>n.id===req)?.name||req).join(', '),level,cost:node.cost};const cost=node.cost;return {ok:c.unlocked&&s.resources.knowledge>=cost,label:s.resources.knowledge>=cost?'UNLOCK':'NEEDS KNOWLEDGE',level,cost};}
export function chooseStarter(s,id){const c=ensureCosmic(s),node=starterCosmicNodes.find(n=>n.id===id);if(!node||s.stats.ascensions<1||c.firstChoice||c.purchased[id]||s.resources.knowledge<node.cost)return false;s.resources.knowledge-=node.cost;c.purchased[id]=1;c.firstChoice=id;return true;}
export function buyCosmic(s,id){const c=ensureCosmic(s),node=cosmicNodes.find(n=>n.id===id),status=cosmicStatus(s,id);if(!node||!status.ok||node.starter&&!c.firstChoice)return false;s.resources.knowledge-=status.cost;c.purchased[id]=1;return true;}
export function cosmicBonuses(s){const out={production:0,research:0,frontier:0,automation:0,click:0,entropy:0};for(const n of cosmicNodes){if(!cosmicLevel(s,n.id))continue;for(const [k,v] of Object.entries(n.effect||{}))out[k]=(out[k]||0)+v;}return out;}
export function starterChoiceAvailable(s){return ensureCosmic(s).unlocked&&!ensureCosmic(s).firstChoice&&s.stats.ascensions===1;}
export {cosmicNodes,cosmicBranches,starterCosmicNodes};
